apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api-service.fullname" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "api-service.fullname" . }}-gcp
    kind: SecretStore
  target:
    name: {{ include "api-service.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbPasswordSecretId | quote }}
    - secretKey: THIRD_PARTY_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.thirdPartyApiKeySecretId | quote }}
