apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-service.serviceAccountName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
  annotations:
    # Binds this Kubernetes ServiceAccount to the GCP service account
    # created by the workload-identity Terraform module - Pods using this
    # KSA transparently authenticate as that GSA, no key file involved.
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccountEmail | quote }}
automountServiceAccountToken: true
